//
//  RestaurantsViewModel.swift
//  Restaurants
//
//  Created by piotr koscielny on 30/5/25.
//

import Foundation

final class RestaurantsViewModel {
    let restaurants: [RestaurantModel] = [
                                          RestaurantModel(name: "Starbucks", description: "A premium coffeehouse chain offering specialty coffee, teas, and pastries. Known for its cozy ambiance and customizable drinks.", image: RestaurantsImages.starbucks, menu:["Pumpkin Spice Latte (Seasonal)","Caramel Macchiato","Iced White Chocolate Mocha","Vanilla Sweet Cream Cold Brew","Double Smoked Bacon Sandwich","Cheese & Fruit Protein Box","Lemon Loaf Cake","Impossible Breakfast Sandwich","Matcha Crème Frappuccino","Chocolate Croissant"], details: "Starbucks is a beverage retailer and the world's leading coffeehouse chain, known for its specialty coffee and other beverages. The company also offers a variety of food items, including pastries, sandwiches, and snacks. Beyond its core business, Starbucks is known for its strong brand presence, global reach, and commitment to sustainability and community engagement.", rating: 5, distance: 4.3, type: "coffe"),
                                          
                                          RestaurantModel(name: "Subway", description: "A fast-food restaurant specializing in made-to-order sandwiches and salads, marketed as a healthier fast-food option.", image: RestaurantsImages.subway, menu: ["Italian B.M.T.", "Veggie Delite", "Chicken & Bacon Ranch Melt", "Tuna Sandwich", "Meatball Marinara", "Buffalo Chicken Sub", "Rotisserie-Style Chicken", "Subway Club", "Sweet Onion Chicken Teriyaki", "Chocolate Chip Cookie"], details: "The restaurant chain, Subway, is a global quick-service restaurant known for its submarine sandwiches, which are split Italian rolls filled with various meats, cheeses, vegetables, and condiments. They are made to order by the customer and are often referred to as subs. The Subway restaurant chain has more than 37,000 locations in nearly 100 countries. ", rating: 2, distance: 12.2, type: "sandwitch"),
                                          
                                          RestaurantModel(name: "KFC", description: "A global fried chicken chain famous for its secret blend of 11 herbs and spices. Known for buckets of crispy chicken and comfort food.", image: RestaurantsImages.kfc, menu: ["Original Recipe Chicken (3pc)", "Extra Crispy Chicken", "Popcorn Nuggets", "Famous Bowl (Mashed Potatoes + Gravy)", "Chicken Sandwich", "Mac & Cheese", "Biscuit with Honey", "Crispy Colonel Sandwich", "Secret Recipe Fries", "Chocolate Chip Cake"], details: "KFC, short for Kentucky Fried Chicken, is an American fast food restaurant chain specializing in fried chicken and chicken sandwiches. Founded by Harland Sanders, it's known for its signature fried chicken and finger lickin' good recipe, which uses a secret blend of 11 herbs and spices.", rating: 1, distance: 33, type: "fast food"),
                                          
                                          RestaurantModel(name: "Pizza Hut", description: "One of the largest pizza chains, offering dine-in, delivery, and takeout options with a variety of pizzas, pastas, and sides.", image: RestaurantsImages.pizzaHut, menu: ["Meat Lover's Pizza", "Supreme Pizza", "Stuffed Crust (Pepperoni)", "Veggie Lover's Pizza", "Buffalo Chicken Pizza", "Garlic Parmesan Wings", "Hershey's Chocolate Dunkers", "Breadsticks with Marinara", "Hawaiian Chicken Pizza", "Cinnamon Sticks"], details: "Pizza Hut is a globally recognized American pizza restaurant chain and franchise, known for its variety of pizzas, including the signature Pan Pizza, along with pasta, salads, and other side dishes. It was founded in 1958 by brothers Dan and Frank Carney in Wichita, Kansas. Pizza Hut is a subsidiary of Yum! Brands, Inc. ", rating: 5, distance: 0.3, type: "pizza"),
                                          
                                          RestaurantModel(name: "Burger King", description: "A major fast-food chain known for flame-grilled burgers, Whoppers, and crispy fries. Competes directly with McDonald’s.", image: RestaurantsImages.burgerKing, menu:["Whopper", "Impossible Whopper", "Chicken Fries", "Bacon King Sandwich", "Rodeo Burger", "French Fries (Large)", "Onion Rings", "Oreo Shake", "Breakfast Croissan'wich", "Hershey's Sundae Pie"] , details: "Burger King is a large international fast-food chain known for its burgers, especially the Whomper. It's the second-largest hamburger chain in the United States, after McDonald's. The company emphasizes high-quality, great-tasting, and affordable food. ", rating: 3, distance: 41.21, type: "fast food"),
                                          
                                          RestaurantModel(name: "Domino’s Pizza", description: "A leading pizza delivery chain famous for its 30-minute delivery guarantee (discontinued but still a key part of its branding).", image: RestaurantsImages.dominos, menu:["ExtravaganZZa Pizza", "Pacific Veggie Pizza", "Buffalo Chicken Pizza", "Philly Cheese Steak Pizza", "Parmesan Bread Bites", "Stuffed Cheesy Bread", "Chocolate Lava Crunch Cakes", "Cinnamon Bread Twists", "Wings (Hot Buffalo)", "Marbled Cookie Brownie"], details: "Domino's Pizza is a large international pizza delivery company, with stores in over 90 countries, including the United States and the United Kingdom. They offer a wide variety of pizza crusts and toppings, as well as other menu items like pasta, oven-baked sandwiches, and chicken wings. Domino's is known for its focus on delivery and online ordering, with innovations like 3D car-top signs and online pizza builders.", rating: 2, distance: 1.2, type: "pizza")]
}
